### ISSUE TITLE
Requires node to be installed at `/usr/bin/node`

### ISSUE THREAD

**Issue by ghost** [allain/bench-csv#1]
https://github.com/allain/bench-csv/blob/master/bin/bench-csv.js#L1

For users (like myself) that have `node` installed using [nvm](https://github.com/creationix/nvm), or use a package manager, node will _not_ be installed in this location. Please replace that line from the script with `/usr/bin/env node` instead.

**Comment by allain** [comment]
good catch, the only issue is that `#!/path ARG` only supports one argument, using `/usr/bin/env node` eats up that argument. The only thing I can think of is to spark a child_process with the correct argument set after figuring out which node to run using `which`

**Comment by allain** [comment]
@mhsjlw - Fixed in v2.2.4. Please confirm.

**Comment by ghost** [comment]
Confirmed to work. Thanks for the quick fix.
